image: evolvingweb/drupal-fpm:ci-8.1
# Uncomment the following lines if you need a full Drupal.
#services:
#  - mariadb:10.5

stages:
  - build
  - deploy

variables:
  THEME_DIR: docroot/themes/custom/yukonca_glider
  BLT: ./vendor/bin/blt
  BLT_DIR: ./vendor/acquia/blt
  DRUPAL_CI_DIR: ./vendor/evolvingweb/drupal-ci
  MYSQL_DATABASE: drupal
  MYSQL_ROOT_PASSWORD: drupal

cache:
  paths:
    - $THEME_DIR/node_modules
    - .composer-cache/

# CI image default to composer v1 for backwords compatibiliy with old sites,
# here we set to version 2. Change to v1 if needed refs #24677 #24833
before_script:
  - composer config -g cache-dir "$(pwd)/.composer-cache"
  - composer self-update --2
  - composer validate --no-check-all --ansi
  - composer install
  - source ~/.bashrc
  - cd $THEME_DIR && nvm install
  - cd $CI_PROJECT_DIR

build:
  stage: build
  script:
    - $BLT validate
    - $BLT source:build --ansi --verbose --no-interaction
    # Uncomment the following lines if you need a full Drupal. @dev alias needs to be added to the repo.
    # - DRUSH="./vendor/bin/drush"
    # - $DRUSH sql-sync @dev @self

deploy_branch:
  stage: deploy
  script:
    - $DRUPAL_CI_DIR/scripts/ssh_key_add
    - $DRUPAL_CI_DIR/scripts/deploy_branch
  only:
    - branches

deploy_tag:
  stage: deploy
  script:
    - $DRUPAL_CI_DIR/scripts/ssh_key_add
    - $DRUPAL_CI_DIR/scripts/deploy_tag
  only:
    - tags

validate_prod:
  stage: deploy
  script:
    - $DRUPAL_CI_DIR/scripts/ssh_key_add
    - $DRUPAL_CI_DIR/acquia/validate-prod-clean
  only:
    - tags
