name: Deploy to Pantheon

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

env:
  PANTHEON_SITE: "<site_uuid>" # Replace with your Pantheon site UUID
  PANTHEON_ENV: "dev" # Set to 'dev', 'test', or 'live'
  THEME_DIR: docroot/themes/custom/mytheme
  MYSQL_DATABASE: drupal
  MYSQL_ROOT_PASSWORD: drupal

jobs:
  build:
    runs-on: ubuntu-latest
    container: evolvingweb/drupal-fpm:ci-8.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Composer
      run: |
        composer config -g cache-dir "$(pwd)/.composer-cache"
        composer self-update --2
        composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Set up Node.js (for theme assets)
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install
        cd $THEME_DIR
        npm install
        npm run build

    - name: Validate and Build Site
      run: |
        ./vendor/bin/blt validate
        ./vendor/bin/blt source:build --verbose

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Composer
      run: |
        composer config -g cache-dir "$(pwd)/.composer-cache"
        composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Set up SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        config: ${{ secrets.DEPLOY_SSH_CONFIG }}
        known_hosts: ${{ secrets.DEPLOY_KNOWN_HOSTS }}

    - name: Deploy to Pantheon
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git remote add pantheon ssh://codeserver.${{ env.PANTHEON_SITE }}@codeserver.dev.pantheon.io:2222/~/repository.git
        git push pantheon main
