name: Deploy to server

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

env:
  THEME_DIR: docroot/themes/custom/yukonca_glider
  BLT: ./vendor/bin/blt
  BLT_DIR: ./vendor/acquia/blt
  DRUPAL_CI_DIR: ./vendor/evolvingweb/drupal-ci
  MYSQL_DATABASE: drupal
  MYSQL_ROOT_PASSWORD: drupal

jobs:
  build:
    container: evolvingweb/drupal-fpm:ci-8.1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Before build
      run: |
        composer config -g cache-dir "$(pwd)/.composer-cache"
        composer self-update --2
        composer validate --no-check-all --ansi
        composer install
    - name: Source Build
      run: |
        CI_PROJECT_DIR="$(pwd)"
        curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
        [ -s "$HOME/.nvm/nvm.sh" ] && \. "$HOME/.nvm/nvm.sh"
        cd $THEME_DIR
        nvm install
        cd $CI_PROJECT_DIR
        $BLT validate
        $BLT source:build --ansi --verbose --no-interaction
    - name: Prepare Deploy Directory
      run: |
        mkdir -p deploy  # Ensure deploy directory exists

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp

    - name: Artifact Deploy to GoDaddy via SFTP
      env:
        DEPLOY_HOST: ${{ secrets.SSH_HOST }}
        DEPLOY_USERNAME: ${{ secrets.SSH_USER }}
        DEPLOY_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        # Define paths
        LOCAL_ARTIFACT_PATH="deploy/"
        REMOTE_DEPLOY_PATH="/public_html/"
        
        # Use lftp to mirror local directory to GoDaddy server
        lftp -c "set ssl:verify-certificate no; \
                 open -u $DEPLOY_USERNAME,$DEPLOY_PASSWORD sftp://$DEPLOY_HOST; \
                 mirror -R --delete --verbose $LOCAL_ARTIFACT_PATH $REMOTE_DEPLOY_PATH"
